ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER ASSIGNMENT_2 IDENTIFIED BY 123;
GRANT CREATE SESSION TO ASSIGNMENT_2;
GRANT DBA TO ASSIGNMENT_2;

-- Granter to the Application
CREATE USER MANAGER IDENTIFIED BY 123456;
GRANT CREATE SESSION TO MANAGER;
GRANT DBA TO MANAGER;